<?php
/* AAC document registry — auto-generated from the disclosure pages.
   'file' = exact filename in /mandatory/pdf/ ; 'title' ; 'section'.
   Edit here if you add new disclosure PDFs. */
$aac_documents = [
    ['file' => 'naac.pdf', 'title' => 'naac', 'section' => 'A. Institute Information — Accreditation & Statutory'],
    ['file' => 'NBA Letter.pdf', 'title' => 'NBA Letter', 'section' => 'A. Institute Information — Accreditation & Statutory'],
    ['file' => 'NIRF_2025.pdf', 'title' => 'NIRF_2025', 'section' => 'A. Institute Information — Accreditation & Statutory'],
    ['file' => 'NOC_DTTE_2025-26.pdf', 'title' => 'NOC_DTTE_2025-26', 'section' => 'A. Institute Information — Accreditation & Statutory'],
    ['file' => 'b) Programmewise list of Faculty.pdf', 'title' => 'b) Programmewise list of Faculty', 'section' => 'B. Details of Academic Programmes'],
    ['file' => 'c_TimeTable_EvenOdd.pdf', 'title' => 'c_TimeTable_EvenOdd', 'section' => 'B. Details of Academic Programmes'],
    ['file' => 'NAAC Certificate.pdf', 'title' => 'NAAC Certificate', 'section' => '1. Status of Accreditation'],
    ['file' => 'NBA Certificate.pdf', 'title' => 'NBA Certificate', 'section' => '1. Status of Accreditation'],
    ['file' => 'TSR.pdf', 'title' => 'TSR', 'section' => '2. Status of Teachers Availability'],
    ['file' => '3(a) No. of Teacher with PhDD.pdf', 'title' => '3(a) No. of Teacher with PhDD', 'section' => '3. Quality of Teachers and Teaching'],
    ['file' => '3(bi) Publication in Wos Scopus.pdf', 'title' => '3(bi) Publication in Wos Scopus', 'section' => '3. Quality of Teachers and Teaching'],
    ['file' => '3(bii) Publication in UCG Care.pdf', 'title' => '3(bii) Publication in UCG Care', 'section' => '3. Quality of Teachers and Teaching'],
    ['file' => '3(biii) Publication only referred Journals.pdf', 'title' => '3(biii) Publication only referred Journals', 'section' => '3. Quality of Teachers and Teaching'],
    ['file' => '3(ci1) publication indexed by WoS SCOPUS.pdf', 'title' => '3(ci1) publication indexed by WoS SCOPUS', 'section' => '3. Quality of Teachers and Teaching'],
    ['file' => '3(ci2) Publication with ISBN No.pdf', 'title' => '3(ci2) Publication with ISBN No', 'section' => '3. Quality of Teachers and Teaching'],
    ['file' => '3(cii) No.of Patent.pdf', 'title' => '3(cii) No.of Patent', 'section' => '3. Quality of Teachers and Teaching'],
    ['file' => '3(d) No.of Book authored.pdf', 'title' => '3(d) No.of Book authored', 'section' => '3. Quality of Teachers and Teaching'],
    ['file' => '3(e) Teaching Plan.pdf', 'title' => '3(e) Teaching Plan', 'section' => '3. Quality of Teachers and Teaching'],
    ['file' => '3(f) No.of LMS.pdf', 'title' => '3(f) No.of LMS', 'section' => '3. Quality of Teachers and Teaching'],
    ['file' => '3(g) Class Room.pdf', 'title' => '3(g) Class Room', 'section' => '3. Quality of Teachers and Teaching'],
    ['file' => '3(h) Teachers using ICT for teaching.pdf', 'title' => '3(h) Teachers using ICT for teaching', 'section' => '3. Quality of Teachers and Teaching'],
    ['file' => '4(a) Best faculty - research award.pdf', 'title' => '4(a) Best faculty - research award', 'section' => '4. Institutional Support for Faculty Development'],
    ['file' => '4(b) Grant of study leave.pdf', 'title' => '4(b) Grant of study leave', 'section' => '4. Institutional Support for Faculty Development'],
    ['file' => '4(c) List of Grant of fund to attend conference seminar etc.pdf', 'title' => '4(c) List of Grant of fund to attend conference seminar etc', 'section' => '4. Institutional Support for Faculty Development'],
    ['file' => '5(a) Availablity of SGRC.pdf', 'title' => '5(a) Availablity of SGRC', 'section' => '5. Grievance Redressal Mechanism'],
    ['file' => '5(b) List of student elected in SGRC.pdf', 'title' => '5(b) List of student elected in SGRC', 'section' => '5. Grievance Redressal Mechanism'],
    ['file' => '5(c) documents related to proceeding SGRC.pdf', 'title' => '5(c) documents related to proceeding SGRC', 'section' => '5. Grievance Redressal Mechanism'],
    ['file' => '5(d) Availablity of Psychiatrist, Psychologist etc..pdf', 'title' => '5(d) Availablity of Psychiatrist, Psychologist etc.', 'section' => '5. Grievance Redressal Mechanism'],
    ['file' => '5(e) Details of SGRC published in Institute website.pdf', 'title' => '5(e) Details of SGRC published in Institute website', 'section' => '5. Grievance Redressal Mechanism'],
    ['file' => '5(f) Students safisfaction_survey.pdf', 'title' => '5(f) Students safisfaction_survey', 'section' => '5. Grievance Redressal Mechanism'],
    ['file' => '5(g) Reports of Proceeding of SGRC sent to University.pdf', 'title' => '5(g) Reports of Proceeding of SGRC sent to University', 'section' => '5. Grievance Redressal Mechanism'],
    ['file' => '6(Exams Support).pdf', 'title' => '6(Exams Support)', 'section' => '6. University Examination Support'],
    ['file' => '7(a) Status of Books.pdf', 'title' => '7(a) Status of Books', 'section' => '7. Status of Library'],
    ['file' => '7(b) Status of Journals.pdf', 'title' => '7(b) Status of Journals', 'section' => '7. Status of Library'],
    ['file' => '8(b) Status of Computer Labs.pdf', 'title' => '8(b) Status of Computer Labs', 'section' => '8. Status of Laboratories'],
    ['file' => '8(bii) No. of Licensed software.pdf', 'title' => '8(bii) No. of Licensed software', 'section' => '8. Status of Laboratories'],
    ['file' => '8(biii) Quality of Internet.pdf', 'title' => '8(biii) Quality of Internet', 'section' => '8. Status of Laboratories'],
    ['file' => '9(a) Conference orgainsed.pdf', 'title' => '9(a) Conference orgainsed', 'section' => '9. Co-curricular Activities'],
    ['file' => '9(b) Seminar Organised.pdf', 'title' => '9(b) Seminar Organised', 'section' => '9. Co-curricular Activities'],
    ['file' => '9(c) FDP Organised.pdf', 'title' => '9(c) FDP Organised', 'section' => '9. Co-curricular Activities'],
    ['file' => '9(d) Workshop organised.pdf', 'title' => '9(d) Workshop organised', 'section' => '9. Co-curricular Activities'],
    ['file' => '9(e) Short Term valued Added prog organised.pdf', 'title' => '9(e) Short Term valued Added prog organised', 'section' => '9. Co-curricular Activities'],
    ['file' => '9(f) Webinar Organised.pdf', 'title' => '9(f) Webinar Organised', 'section' => '9. Co-curricular Activities'],
    ['file' => 'Seminar_merged.pdf', 'title' => 'Seminar_merged', 'section' => '9. Co-curricular Activities'],
    ['file' => '10(a) Journals.pdf', 'title' => '10(a) Journals', 'section' => '10. Publications of the Institution'],
    ['file' => '10(b) Magazines.pdf', 'title' => '10(b) Magazines', 'section' => '10. Publications of the Institution'],
    ['file' => '10(b) Newsletter.pdf', 'title' => '10(b) Newsletter', 'section' => '10. Publications of the Institution'],
    ['file' => 'iitmjigyasa.pdf', 'title' => 'iitmjigyasa', 'section' => '10. Publications of the Institution'],
    ['file' => 'mock11a.pdf', 'title' => 'mock11a', 'section' => '11. Students Personality Development'],
    ['file' => '11(a) Role Play.pdf', 'title' => '11(a) Role Play', 'section' => '11. Students Personality Development'],
    ['file' => 'gd11a.pdf', 'title' => 'gd11a', 'section' => '11. Students Personality Development'],
    ['file' => '11(a) Workshop.pdf', 'title' => '11(a) Workshop', 'section' => '11. Students Personality Development'],
    ['file' => '11(a1) Competition.pdf', 'title' => '11(a1) Competition', 'section' => '11. Students Personality Development'],
    ['file' => 'language lab.pdf', 'title' => 'language lab', 'section' => '11. Students Personality Development'],
    ['file' => 'IITM Labs.docx.pdf', 'title' => 'IITM Labs.docx', 'section' => '11. Students Personality Development'],
    ['file' => 'nssncc.pdf', 'title' => 'nssncc', 'section' => '11. Students Personality Development'],
    ['file' => 'counsellor.pdf', 'title' => 'counsellor', 'section' => '11. Students Personality Development'],
    ['file' => '11(c) Sport Facilities.pdf', 'title' => '11(c) Sport Facilities', 'section' => '11. Students Personality Development'],
    ['file' => '12(i) List of students passed.pdf', 'title' => '12(i) List of students passed', 'section' => '12. Status of Placement'],
    ['file' => '12(ii) List of Eligible Students.pdf', 'title' => '12(ii) List of Eligible Students', 'section' => '12. Status of Placement'],
    ['file' => '12(iii) Student going for higher education.pdf', 'title' => '12(iii) Student going for higher education', 'section' => '12. Status of Placement'],
    ['file' => '12(iv) Student Placed.pdf', 'title' => '12(iv) Student Placed', 'section' => '12. Status of Placement'],
    ['file' => '12(vii) No.of company visited.pdf', 'title' => '12(vii) No.of company visited', 'section' => '12. Status of Placement'],
    ['file' => '12(viii) Average Salary offered.pdf', 'title' => '12(viii) Average Salary offered', 'section' => '12. Status of Placement'],
    ['file' => '12(x) Entrepreneurship Activities.pdf', 'title' => '12(x) Entrepreneurship Activities', 'section' => '12. Status of Placement'],
    ['file' => '13i Faculty Seating.pdf', 'title' => '13i Faculty Seating', 'section' => '13. General Parameters'],
    ['file' => '13iii Girls common Room.pdf', 'title' => '13iii Girls common Room', 'section' => '13. General Parameters'],
    ['file' => '13iv Cleanliness of Toilets.pdf', 'title' => '13iv Cleanliness of Toilets', 'section' => '13. General Parameters'],
    ['file' => '13(v)Students Canteen and Drinking Water.pdf', 'title' => '13(v)Students Canteen and Drinking Water', 'section' => '13. General Parameters'],
    ['file' => 'policyu.pdf', 'title' => 'policyu', 'section' => '14. Facilities Available'],
    ['file' => '14(b) Alumni_students feedback.pdf', 'title' => '14(b) Alumni_students feedback', 'section' => '14. Facilities Available'],
    ['file' => 'Compliance.pdf', 'title' => 'Compliance', 'section' => '15. Removal of Deficiencies'],
];
