<?php
// FAQ data for the BBA programme.
// Generated from the institute's master FAQ document; edit here to update site copy.
$course_faq_program = 'BBA';
$course_faq_title   = 'BBA — Frequently Asked Questions';
$course_faq_intro   = 'Everything you need to know about IITM\'s BBA programme — eligibility, entrance exams, fees, curriculum, internships and placements.';
$course_faqs = [
    ['q' => 'What is the eligibility criteria to join in BBA?', 'a' => 'Candidate must be pass in 12th Class of CBSE(10+2) or equivalent with a minimum of 50% marks in aggregate and also should have passed English (core or elective or functional) as a subject.'],
    ['q' => 'Is there an entrance exam-based admission process?', 'a' => 'Yes, admission is based on qualifying either of the entrance exams i.e GGSIPU CET or CUET.For more information, refer to: https://ipu.admissions.nic.in/'],
    ['q' => 'Are CUET results accepted?', 'a' => 'Yes, IITM (Information Campus) accepts CUET scores. At least one of these subjects should be there; Section IA: English (code 101), Section II: Business Studies (Code 305) or Section III: General Test (code 501) for General Awareness/ Logic and Analytical Ability'],
    ['q' => 'What is the cutoff for taking admission in BBA?', 'a' => 'For latest cutoffs refer to https://ipu.admissions.nic.in/'],
    ['q' => 'Is there any stream restriction for joining BBA?', 'a' => 'Students from any stream can apply.'],
    ['q' => 'Can I take admission directly without any entrance exam?', 'a' => 'Students need to qualify either CET or CUET for admission and participate in the counselling of GGSIPU.'],
    ['q' => 'Is multiple entry-exit option available?', 'a' => 'Yes, the programme offers flexible entry and exit options under NEP 2020. The total duration of the degree programme is 3 years. Upon successful completion of 3 years, they can opt for 4 year BBA with Honors or Research.'],
    ['q' => 'What are the subjects studied in BBA?', 'a' => 'Core subjects like Principles and Practices of Management, Business Economics, Indian Knowledge System, Business & Environmental Law, Business Analytics, etc. For more details: http://www.ipu.ac.in/usms/Scheme_Syllabus.php'],
    ['q' => 'Does Institute offers any specializations?', 'a' => 'Institute offers various specializations which includes Management, Marketing, Finance, HR, International Business, Entrepreneurship. Institute follows NEP 2020 policy as per GGSIPU.'],
    ['q' => 'Is there any choice in subjects?', 'a' => 'Yes, as per GGSIPU curriculum, Institute offers basket of multi-disciplinary courses laying emphasis on critical and creative thinking through a variety of courses from third semester onwards. For more details: http://www.ipu.ac.in/usms/Scheme_Syllabus.php'],
    ['q' => 'Are there any smart classrooms in the college?', 'a' => 'Yes, IITM (Information Campus) provides state-of-the-art infrastructure and modern classroom facilities, including smart classrooms equipped with projectors, modular seating arrangements, centralized air conditioning, and other advanced learning amenities like Simulation labs, computer labs, Drone Technology, Multimedia Studio.'],
    ['q' => 'Is there Wi-Fi on campus?', 'a' => 'Yes, Institute has Digitally Connected Campus with Wi-Fi facility.'],
    ['q' => 'What other infrastructural facilities does the institute provide?', 'a' => 'The institute offers a centrally air-conditioned campus equipped with modern infrastructure and learning facilities. These include smart classrooms, a well-stocked library, computer laboratories, an auditorium, seminar halls, video and audio studios, a multimedia centre, and advanced designing and editing labs. The campus also provides a Yoga and Meditation Centre, a Fitness & Wellness Studio, an Apple-based iMac Café, and a hygienic canteen for students and staff.'],
    ['q' => 'How safe is the campus environment?', 'a' => 'The campus ensures a safe and secure environment for students through 24x7 CCTV surveillance and dedicated support systems such as the Internal Complaints Committee, Proctorial Board, Anti-Ragging Committee, and Grievance Redressal Committee.'],
    ['q' => 'Does IITM have hostel and transport facility?', 'a' => 'No, IITM does not provide hostel and transport facilities. However, several PG accommodations are available in the nearby area, and the institute has tie-ups with suitable PG options for students’ convenience.'],
    ['q' => 'Does IITM have provision for education loan?', 'a' => 'The institute offers complete support to students applying for education loans.'],
    ['q' => 'Does IITM have sports facility?', 'a' => 'Yes, IITM has both indoor such as carom, chess, table tennis etc and outdoor sports facility such as cricket, volleyball, football, badminton, tug-of-war etc.'],
    ['q' => 'Does IITM have NSS/ NCC facility?', 'a' => 'Yes, IITM offers both NSS and NCC to students, provides opportunities to participate in social service activities, leadership training, and discipline-oriented programmes'],
    ['q' => 'How is campus life at IITM?', 'a' => 'IITM offers a vibrant campus life with multiple student societies such as NexVerse, Managinius, Riwayat, Internware, Management club, Commerce club, etc and many more. The institute also hosts various cultural and academic events and festivals, including Anugoonj, Fiesta, Management Fest, MediaX, Comparv and other engaging activities throughout the year for Holistic development'],
    ['q' => 'What is the fee structure of the BBA program?', 'a' => 'The fee for AY 25-26 was INR 1,49,900(Annual).'],
    ['q' => 'Are there any scholarships provided?', 'a' => 'Yes, Merit based scholarships are available on pre-admission basis and students can avail government scholarships also.'],
    ['q' => 'What is the security amount?', 'a' => 'A refundable security deposit of INR 10,000 is taken at the time of admission.'],
    ['q' => 'Does the college provide internships?', 'a' => 'Yes, college provides full support for internships via a dedicated internware cell.'],
    ['q' => 'What is the placement percentage of BBA students?', 'a' => 'Placement percentage is 99.06%. of students eligible and seeking placements'],
    ['q' => 'Which are the top recruiters for BBA?', 'a' => 'Top companies such as TCS, Infosys, Amazon, Cisco, Genpact, Wipro, Evalueserve, Deloitte, ICICI Bank and many more recruits our BBA students.'],
    ['q' => 'What is the average salary package offered to BBA graduates?', 'a' => 'Average package is ₹4.21 LPA.'],
    ['q' => 'What kind of industry exposure do students get at the college?', 'a' => 'Institute provides strong industry exposure through industrial visits, student exchange programmes, international student immersion programmes, live projects, internships, expert sessions by industry professionals, workshops, seminars, and corporate interactions. Students also get opportunities to participate in management fests, skill-development programs, and practical learning activities to enhance their industry readiness.'],
    ['q' => 'What are the job profiles offered after doing BBA from IITM?', 'a' => 'After completing BBA from IITM, students can explore career opportunities in areas such as Human Resource Management, Sales and Marketing, Business Development, Operations, Customer Relationship Management, and Business Analytics across different sectors.'],
    ['q' => 'What documents are to be provided for getting admission?', 'a' => 'Documents include 10th & 12th mark sheets, ID proof, photos, reservation certificate(if applicable), CET admit card and entrance scorecard.'],
    ['q' => 'Does the college offer guidance for doing MBA?', 'a' => 'Yes, support for higher studies is provided like preparatory leaves and career counselling sessions.It also gives preference to IITM Alumni for MBA at Institute'],
];
