<?php
// FAQ data for the MBA programme.
// Generated from the institute's master FAQ document; edit here to update site copy.
$course_faq_program = 'MBA';
$course_faq_title   = 'MBA — Frequently Asked Questions';
$course_faq_intro   = 'Quick answers to the questions prospective MBA candidates and parents ask us most often — admissions, fees, specializations, campus life and placements.';
$course_faqs = [
    ['q' => 'What is the eligibility criteria to join in MBA?', 'a' => 'Candidates must fulfill any one of the following criteria:
Possess a recognized Bachelor’s Degree of minimum 3 years’ duration in any discipline with at least 50% aggregate marks. 		OR
Possess a Bachelor’s Degree in Engineering, Technology, or any other discipline, or an equivalent qualification recognized by the competent authority, with at least 50% aggregate marks. 						OR
Have passed the Final Examination of:
the Institute of Chartered Accountants of India or its equivalent in England,
the Institute of Cost Accountants of India (formerly ICWAI) or its equivalent in England, or
the Institute of Company Secretaries of India.'],
    ['q' => 'Is there an entrance exam-based admission process?', 'a' => 'The candidates seeking admission in MBA programme must have a valid score of CAT/CMAT/ GGSIPU PG CUET.'],
    ['q' => 'What is the cutoff for taking admission in MBA?', 'a' => 'For latest cutoffs visit https://ipu.admissions.nic.in/'],
    ['q' => 'Is there any stream restriction for joining MBA?', 'a' => 'Students from any stream can apply.'],
    ['q' => 'Can I take admission directly without any entrance exam?', 'a' => 'Students need to qualify CAT, IPU CET, or CMAT for admission. As per university, institute reserves 10% seats for Direct Admissions based on merit.'],
    ['q' => 'Is multiple entry-exit option available?', 'a' => 'Yes, under the flexible entry and exit framework envisaged in the National Education Policy 2020, a student enrolled in the MBA programme may opt to exit after successful completion of one year with a Postgraduate Diploma in Management (PGDM) / Postgraduate Diploma, as applicable. Students who successfully complete the 2 years of the programme will be awarded MBA Degree.'],
    ['q' => 'What are the subjects studied in MBA?', 'a' => 'Core subjects like Principles of Management, Business Economics, Decision Techniques, Business Law, Strategic Management, Entrepreneurship, Business Analytics, etc. For more information, visit http://www.ipu.ac.in/usms/Scheme_Syllabus.php'],
    ['q' => 'Does Institute offers any specializations?', 'a' => 'Institute offers dual specializations which include Management, Marketing, Finance, HR, International Business, IT, Operations. Institute follows NEP 2020 policy as per GGSIPU. For more details, visit http://www.ipu.ac.in/usms/Scheme_Syllabus.php'],
    ['q' => 'Are there any smart classrooms in the college?', 'a' => 'Yes, IITM (Information Campus) provides state-of-the-art infrastructure and modern classroom facilities, including smart classrooms equipped with projectors, modular seating arrangements, centralized air conditioning, and other advanced learning amenities.'],
    ['q' => 'Is there Wi-Fi on campus?', 'a' => 'Yes, Institute has Digitally Connected Campus with Wi-Fi facility.'],
    ['q' => 'What other infrastructural facilities does the institute provide?', 'a' => 'The institute offers a centrally air-conditioned campus equipped with modern infrastructure and learning facilities. These include smart classrooms, a well-stocked library, computer laboratories, an auditorium, seminar halls, video and audio studios, a multimedia centre, and advanced designing and editing labs. The campus also provides a Yoga and Meditation Centre, a Fitness & Wellness Studio, an Apple-based iMac Café, and a hygienic canteen for students and staff.'],
    ['q' => 'How safe is the campus environment?', 'a' => 'The campus ensures a safe and secure environment for students through 24x7 CCTV surveillance and dedicated support systems such as the Internal Complaints Committee, Proctorial Board, Anti-Ragging Committee, and Grievance Redressal Committee.'],
    ['q' => 'Does IITM (Information Campus) have hostel and transport facility?', 'a' => 'No, IITM (Information Campus) does not provide hostel and transport facilities. However, several PG accommodations are available in the nearby area, and the institute has tie-ups with suitable PG options for students’ convenience.'],
    ['q' => 'Does IITM (Information Campus) have provision for education loan?', 'a' => 'The institute offers complete support to students applying for education loans.'],
    ['q' => 'Does IITM (Information Campus) have sports facility?', 'a' => 'Yes, IITM (Information Campus) has indoor sports such as carom, chess, table tennis, etc., outdoor sports facility such as cricket, volleyball, football, badminton, tug-of-war etc and e-sports facility.'],
    ['q' => 'How is campus life at IITM (Information Campus)?', 'a' => 'IITM (Information Campus) offers a vibrant campus life with multiple student societies such as NexVerse, Managinius, Riwayat, Internware, Management club, Commerce club, etc and many more. The institute also hosts various cultural and academic events and festivals, including Anugoonj, Fiesta, Management Fest, MediaX, Comparv and other engaging activities throughout the year for Holistic development.'],
    ['q' => 'What is the fee structure of the MBA program?', 'a' => 'The fee for AY 25-26 was INR 2,21,900(Annual)'],
    ['q' => 'Are there any scholarships provided?', 'a' => 'Yes, Merit based scholarships are available on pre-admission basis and students can avail government scholarships also.'],
    ['q' => 'What is the security amount?', 'a' => 'A refundable security deposit of INR 10,000 is taken at the time of admission.'],
    ['q' => 'Does the college provide internships?', 'a' => 'Yes, college provides full support for internships via a dedicated internware cell.'],
    ['q' => 'What is the placement percentage of MBA students?', 'a' => 'Placement percentage is 97.5% of students eligible and seeking placements.'],
    ['q' => 'Which are the top recruiters for MBA?', 'a' => 'Top companies such as TCS, Infosys, Amazon, Cisco, Genpact, Wipro, Evalueserve, Deloitte, ICICI Bank and many more recruits our MBA students.'],
    ['q' => 'What is the average & highest salary package offered to MBA graduates?', 'a' => 'Average package is ₹4.96 LPA. Highest package is ₹13.36 LPA.'],
    ['q' => 'What kind of industry exposure do students get at the college?', 'a' => 'Institute provides strong industry exposure through industrial visits, student exchange programmes, international student immersion programmes, live projects, internships, expert sessions by industry professionals, workshops, seminars, and corporate interactions. Students also get opportunities to participate in management fests, skill-development programs, and practical learning activities to enhance their industry readiness.'],
    ['q' => 'What are the job profiles offered after doing MBA from IITM (Information Campus)?', 'a' => 'After completing MBA from IITM (Information Campus), students can explore career opportunities in areas such as Human Resource Management, Sales and Marketing, Business Development, Operations, Customer Relationship Management, and Business Analytics across different sectors.'],
    ['q' => 'What documents are to be provided for getting admission?', 'a' => 'Documents include 10th, 12th & graduation mark sheets, ID proof, photos, reservation certificate & gap year affidavit (if applicable), CET admit card (if applicable) and entrance scorecard.'],
    ['q' => 'What are the job prospects after pursuing MBA?', 'a' => 'An MBA can open doors to careers in management, consulting, finance, marketing, operations, analytics, entrepreneurship, and technology-driven business roles. However, the opportunities you get after an MBA depend on several factors, such as your specialization, the reputation of your institute, prior work experience, communication skills, internships, and the overall demand in the industry'],
    ['q' => 'Are students encouraged to participate in research, competitions, and case study events?', 'a' => 'Yes, students are encouraged to participate in research activities, business plan competitions, management fests, case study competitions, hackathons, and inter-college events to enhance their analytical, managerial, and leadership skills.'],
    ['q' => 'Does the MBA programme include practical learning opportunities?', 'a' => 'Yes, the programme emphasizes practical learning through internships, live projects, case studies, industrial visits, presentations, group discussions, and simulation-based activities to bridge the gap between academics and industry requirements.'],
    ['q' => 'Why should students choose IITM (Information Campus) for MBA?', 'a' => 'IITM (Information Campus) offers quality education, experienced faculty, industry-oriented curriculum, strong placement support, modern infrastructure, industry exposure, skill-development opportunities, and a vibrant campus environment focused on holistic student development.'],
];
