<?php
// FAQ data for the MCA programme.
// Generated from the institute's master FAQ document; edit here to update site copy.
$course_faq_program = 'MCA';
$course_faq_title   = 'MCA — Frequently Asked Questions';
$course_faq_intro   = 'Common questions about the MCA programme — eligibility, NIMCET/CET/CUET admission, infrastructure, internships and placements.';
$course_faqs = [
    ['q' => 'What is the eligibility criteria for MCA admission?', 'a' => 'Passed BCA/B.Sc. (Computer Science)/B.Sc.(Technology) or equivalent or Passed at least 03 years Bachelors Degree with mathematics/statistics at 10+2 level or graduation level. Obtained at least 50% marks (45% marks in case of candidates belonging to reserved category) in the qualifying examinations.'],
    ['q' => 'How can I apply for MCA admission?', 'a' => 'The admission to MCA will be on the basis of NIMCET/CET/CUET in following order of priority:
1. NIMCET
2. CET (If Seats remain vacant after admission through NIMCET counselling on the basis of merit of NIMCET, the University will consider admission in MCA on the basis of CET. The vacant seats after exhausting the merit filled through the merit list of CUET'],
    ['q' => 'What documents are required for MCA admission?', 'a' => 'Common documents include graduation mark sheets, identity proof, photographs, transfer certificate, migration certificate, and category certificate if applicable. For more details visit: https://iitmjanakpuri.com/admissions/docs/Check%20List_u1.pdf'],
    ['q' => 'What was the previous year cutoff for MCA?', 'a' => 'The previous year cutoff varied depending on category, seat availability, and number of applicants. Students can check official admission updates for details.'],
    ['q' => 'Can I get direct admission in MCA?', 'a' => 'Direct admission may be available based on eligibility criteria, seat availability, and institute admission policies for the selected session.'],
    ['q' => 'What is the duration of the MCA program?', 'a' => 'The MCA program generally has a duration of two years and is divided into Four semesters as per university guidelines.'],
    ['q' => 'What subjects are included in the MCA course?', 'a' => 'The MCA curriculum generally includes programming, database management, networking, software engineering, web development, and project work. For more details check syllabus: https://iitmjanakpuri.com/academics/images/syllmca2years171220.pdf'],
    ['q' => 'Does the college provide practical lab sessions for MCA students?', 'a' => 'Yes, regular practical lab sessions are conducted to improve coding skills, software development knowledge, and hands-on technical experience.'],
    ['q' => 'Does the college provide study material for MCA students?', 'a' => 'Yes, faculty members provide notes, presentations, assignments, and digital resources to support classroom learning and exam preparation.'],
    ['q' => 'Are internships available for MCA students?', 'a' => 'Yes, internship opportunities are available through placement support, industry collaborations, and student applications. Companies like DUCAT, GenixEra, S.O. Infotech, Moncerra, and emerging tech startups offer internships to students.'],
    ['q' => 'What is the attendance requirement for MCA students?', 'a' => 'Students must maintain 75% attendance as per university norms to remain eligible for exams.'],
    ['q' => 'Does the college provide placements for MCA students?', 'a' => 'Yes, the college provides placement support through campus recruitment drives, career guidance, and company interactions. For more details visit: https://www.iitmjanakpuri.com/placements/placements.php'],
    ['q' => 'Which companies visit for MCA placements?', 'a' => 'Busy Infotech, CronJ IT Technologies Pvt. Ltd., Decimal Technologies, Entab Infotech, Financial Spectra, Hexaview Technologies, Infosys, Innodata, NTT Data, Tech Mahindra, and Zoxima Solutions Pvt. Ltd etc.'],
    ['q' => 'What is the highest placement package for MCA students?', 'a' => 'Highest MCA package reaches up to 6 LPA with placements in reputed IT companies and growing startups.'],
    ['q' => 'Are mock interviews conducted for MCA students?', 'a' => 'Yes, mock interviews and group discussion sessions are conducted to improve communication skills and placement readiness.'],
    ['q' => 'Does the college provide placement training for MCA students?', 'a' => 'Yes, placement training includes aptitude preparation, coding practice, resume building, and interview guidance sessions.'],
    ['q' => 'Are coding clubs or technical societies available on campus?', 'a' => 'Yes, technical clubs and coding societies help students improve programming skills and participate in collaborative learning activities. For more details visit: https://www.iitmjanakpuri.com/academics/Committee%20List%202025-26.pdf'],
    ['q' => 'What infrastructure facilities are available for MCA students?', 'a' => 'The college provides smart classrooms, computer labs, Wi-Fi, seminar halls, library facilities, and modern learning resources. For more details visit: https://www.iitmjanakpuri.com/infrastructure/infrastructure.php'],
    ['q' => 'How can MCA students access e-resources and online learning materials?', 'a' => 'Students can access e-books, journals, notes, and online learning resources through the student portal and library systems. For more details visit: https://www.iitmjanakpuri.com/Library/'],
    ['q' => 'Are scholarships available for MCA students?', 'a' => 'Yes, scholarships may be offered based on merit, category, academic performance, or government scholarship schemes. For more details visit: https://iitmjanakpuri.com/scholarships/scholarships.php'],
    ['q' => 'Which renowned personalities have visited the college?', 'a' => 'The college may invite industry experts, motivational speakers, academicians, and public personalities during special events and seminars.'],
    ['q' => 'Does the college organize coding workshops and hackathons?', 'a' => 'Yes, coding workshops, technical events, and hackathons are organized regularly to enhance programming and innovation skills among students.'],
    ['q' => 'Is library access available for MCA students?', 'a' => 'Yes, MCA students can access the library for books, journals, research materials, and digital learning resources.'],
    ['q' => 'What job profiles are offered after completing MCA?', 'a' => 'MCA graduates may work as software developers, web developers, data analysts, system administrators, testers, or technical consultants.'],
    ['q' => 'Are project-based learning opportunities available in MCA?', 'a' => 'Yes, students work on academic and industry-based projects to gain practical exposure and improve problem-solving abilities.'],
    ['q' => 'Does the MCA programme include industry-oriented certifications?', 'a' => 'Yes, students get opportunities to attend certification workshops, skill-development programmes, and training sessions in emerging technologies such as Python, Data Analytics, Cloud Computing, AI, and Web Development.'],
    ['q' => 'Are live projects included in the MCA curriculum?', 'a' => 'Yes, MCA students work on live projects, mini-projects during the 2 years programme as a part of curriculum to gain practical exposure and real-world software development experience'],
    ['q' => 'Is there any support for entrepreneurship or startups for MCA students?', 'a' => 'Yes, the institute encourages innovation and entrepreneurship through workshops, mentoring sessions, startup awareness programmes, and project-based learning activities as a regular practice. It also has incubation cell and entrepreneurship cell to support student creativity and initiatives in the field of technology'],
    ['q' => 'What soft skills training is provided to MCA students?', 'a' => 'The institute provides training in communication skills, teamwork, presentation skills, aptitude, personality development, and interview preparation to improve overall employability.'],
    ['q' => 'Why should students choose IITM Janakpuri for MCA?', 'a' => 'IITM Janakpuri offers quality technical education, experienced faculty, practical learning opportunities, modern infrastructure, placement support, industry interaction, and skill-development activities to prepare students for successful IT careers.'],
];
